<!DOCTYPE html>
<html lang="en">
<head>
 <title>php</title>
</head>
<body>
  <center>
    <table>
        <tr>
            <th>S.No</th>
            <th>Name</th>
            <th>City</th>
            <th>Email</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Nikita</td>
            <td>Bhopal</td>
            <td>nikitanimore@gmail.com</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Neeraj</td>
            <td>harda</td>
            <td>NeerajRathore@gmail.com</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Neha</td>
            <td>Indore</td>
            <td>nehanimore@gmail.com</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Yogita</td>
            <td>Indrapuri</td>
            <td>Yogitanimore@gmail.com</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Saloni</td>
            <td>Bangloru</td>
            <td>salonibanloru@gmail.com</td>
        </tr>
    </table>
  </center>  
</body>
</html>